Entry.create!(name: "Aditya")
Entry.create!(name: "Matz")
Entry.create!(name: "Ryan Bates")
Entry.create!(name: "Yahuda Katz")
Entry.create!(name: "Katrina Kaif")
Entry.create!(name: "Sunny Leone")
Entry.create!(name: "Sachin Tendulkar")
Entry.create!(name: "Roger Federer")
Entry.create!(name: "Tiger Woods")
Entry.create!(name: "Steve Jobs")
